
----------------------------------------------
Run case  1:  -unnamed- 

alpha        ->  alpha       =   -6.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  2:  -unnamed- 

alpha        ->  alpha       =   -4.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  3:  -unnamed- 

alpha        ->  alpha       =   -2.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  4:  -unnamed- 

alpha        ->  alpha       =   0.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  5:  -unnamed- 

alpha        ->  alpha       =   2.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  6:  -unnamed- 

alpha        ->  alpha       =   4.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  7:  -unnamed- 

alpha        ->  alpha       =   6.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  8:  -unnamed- 

alpha        ->  alpha       =   8.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  9:  -unnamed- 

alpha        ->  alpha       =   10.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  10:  -unnamed- 

alpha        ->  alpha       =   12.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  11:  -unnamed- 

alpha        ->  alpha       =   14.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  12:  -unnamed- 

alpha        ->  alpha       =   16.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  13:  -unnamed- 

alpha        ->  alpha       =   18.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
----------------------------------------------
Run case  14:  -unnamed- 

alpha        ->  alpha       =   20.00000
beta         ->  beta        =   0.00000
pb/2V        ->  pb/2V       =   0.00000
qc/2V        ->  qc/2V       =   0.00000
rb/2V        ->  rb/2V       =   0.00000
flap         ->  flap        =   0.00000
aileron      ->  aileron     =   0.00000
elevator     ->  elevator    =   0.00000
rudder       ->  rudder      =   0.00000
